jobs:
  build_site:
    docker:
      - image: cimg/base:latest
    steps:
      - checkout
      - run: ./build.sh
  build_image:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          echo "Building Homepage"
          ls -l
          docker build -t colinbruner/homepage:latest .
workflows:
  version: 2
  build_site_and_image:
    jobs:
      - build_site
      - build_docker

