jobs:
  build-site:
    docker:
      - image: cimg/base:latest
    steps:
      - checkout
      - run: ./build.sh
  build-docker:
    docker:
      - image: docker:latest
      - setup_remote_docker
    steps:
      - checkout
      - run: |
          echo "Building Homepage"
          ls -l
          docker build -t colinbruner/homepage:latest .
workflows:
  version: 2
  build_and_test:
    jobs:
      - build-site
      - build-docker

