version: 2
jobs:
  build:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          echo "Building Homepage"
          ls -l
          docker build -t colinbruner/homepage:latest .
