jobs:
  build_site:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: ./build.sh
      - run: pwd
      - run: ls -l
      # Generated site assets
      - persist_to_workspace:
          root: ./public

  build_image:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          # Relative path to to current working directory
          at: public
      - run: |
          echo "Building Homepage"
          ls -l
          docker build -t colinbruner/homepage:latest .
workflows:
  version: 2
  build_site_and_image:
    jobs:
      - build_site
      - build_image:
          requires:
            - build_site

