jobs:
  build_site:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: ./build.sh
      # Generated site assets
      - persist_to_workspace:
          root: workspace
          paths:
            - public
  build_image:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          # Relative path to to current working directory
          at: workspace
      - run: |
          echo "Logging into Docker hub"
          echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USER} --password-stdin

          echo "Building Homepage"
          docker build -t colinbruner/homepage:latest .
          docker build -t colinbruner/homepage:build-${CIRCLE_BUILD_NUM} .

          echo "Pushing image"
          docker push colinbruner/homepage:latest
          docker push colinbruner/homepage:build-${CIRCLE_BUILD_NUM}
workflows:
  version: 2
  build_site_and_image:
    jobs:
      - build_site
      - build_image:
          requires:
            - build_site

