jobs:
  build_site:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: ./build.sh
      # Generated site assets
      - persist_to_workspace:
          root: workspace
          paths:
            - public
  build_and_push_image:
    environment:
      IMAGE_NAME: colinbruner/homepage
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          # Relative path to to current working directory
          at: workspace
      - run: 
          name: Build Image
          command: |
            echo "Building Image"
            docker build -t $IMAGE_NAME:latest .
            docker build -t $IMAGE_NAME:build-${CIRCLE_BUILD_NUM} .

      - run:
          name: Login and Push Image
          command: |
            echo "Logging into DockerHub"
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
            echo "Pushing image"
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:build-${CIRCLE_BUILD_NUM}

workflows:
  version: 2
  build_site_and_image:
    jobs:
      - build_site
      - build_and_push_image:
          requires:
            - build_site

