jobs:
  generate_site:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: ./scripts/build.sh
workflows:
  version: 2
  generate_and_sync_site:
    jobs:
      - generate_site
