jobs:
  generate_site:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: cd site && ./build.sh
      # Generated site assets
      - persist_to_workspace:
          root: site/workspace
          paths:
            - public
  sync_to_s3:
    docker:
      - image: mesosphere/aws-cli
    steps:
      - checkout
      - attach_workspace:
          at: workspace
      - run:
          name: Sync s3 
          command: |
            echo "Syncing 'workspace/public' to s3"
            ls -l
            ls -l *
            pwd
            ./scripts/sync.sh
  build_and_push_image:
    environment:
      IMAGE_NAME: cbruner/homepage
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: Build Image
          command: |
            echo "Building Image"
            docker build -t $IMAGE_NAME:latest .
            docker build -t $IMAGE_NAME:build-${CIRCLE_BUILD_NUM} .

      - run:
          name: Login and Push Image
          command: |
            echo "Logging into DockerHub"
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
            echo "Pushing image"
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:build-${CIRCLE_BUILD_NUM}

workflows:
  version: 2
  build_site_and_image:
    jobs:
      - generate_site
      - build_and_push_image
      - sync_to_s3:
          requires:
            - generate_site

