#baseurl = "https://www.colinbruner.com"
#baseurl = ""
title = "Colin Bruner"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

[params]
    author = "Colin Bruner"
    info = "Linux Site Reliability Engineer and lover of travel"
    description = "Colin Bruner's personal website"
    keywords = "blog,developer,personal"
    avatarurl = "img/profile.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    #footercontent = "Web."

    hidecredits = true
    hidecopyright = true

    rtl = false
    math = false
    #custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/colinbruner/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 2
    url = "https://www.linkedin.com/in/colin-bruner-b1361484/"
[[params.social]]
    name = "Instagram"
    icon = "fab fa-instagram fa-2x"
    weight = 3
    url = "https://www.instagram.com/colinbruner/"

# Menu links
[[menu.main]]
    name = "About"
    weight = 1
    url  = "/about/"
[[menu.main]]
    name = "Resume"
    weight = 2
    url = "/documents/resume.pdf"
[[menu.main]]
    name = "Blog"
    weight = 3
    url  = "/posts/"
[[menu.main]]
    name = "Photos"
    weight = 4
    url = "https://www.instagram.com/colinbruner/"
