apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: homepage
  labels:
    app: web
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 20%
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: cbruner/homepage:latest
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - name: certs-volume
              mountPath: /etc/nginx/secrets
              readOnly: true
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
      nodeSelector:
        kubernetes.io/arch: arm
      volumes:
        - name: certs-volume
          secret:
            secretName: homepage-certs
