apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: homepage
  labels:
    app: web
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30080
      name: http
  selector:
    app: web
