- name: Build and push Docker images
  uses: docker/build-push-action@v1
  with:
    username: ${{ secrets.DOCKER_USERNAME }}
    password: ${{ secrets.DOCKER_PASSWORD }}
    repository: cbruner/homepage
    tag_with_ref: true
    tag_with_sha: true
